package com.mohammadbahrami.border;

import android.content.ContentValues;
import android.content.Context;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteOpenHelper;
import org.json.JSONArray;
import org.json.JSONObject;
import java.util.ArrayList;
import java.util.List;

public class DatabaseHelper extends SQLiteOpenHelper {
    public static final String[] STATUSES = {"ثبت شده", "پارکینگ پایین", "باسکول کرده", "پارکینگ بالا", "وارد عراق"};
    public DatabaseHelper(Context context) { super(context, "border_manager.db", null, 3); }
    @Override public void onCreate(SQLiteDatabase db) {
        db.execSQL("CREATE TABLE trucks (id INTEGER PRIMARY KEY AUTOINCREMENT, plate TEXT NOT NULL, driver TEXT, phone TEXT, cargo TEXT, owner TEXT, broker TEXT, origin TEXT, parking TEXT, weight TEXT, status INTEGER DEFAULT 0, created_at INTEGER, entry_date TEXT, exit_date TEXT, border_status TEXT)");
        db.execSQL("CREATE TABLE status_history (id INTEGER PRIMARY KEY AUTOINCREMENT, truck_id INTEGER NOT NULL, event_date TEXT NOT NULL, status INTEGER NOT NULL, note TEXT, created_at INTEGER)");
    }
    @Override public void onUpgrade(SQLiteDatabase db,int old,int n){
        if(old<2){db.execSQL("ALTER TABLE trucks ADD COLUMN entry_date TEXT");db.execSQL("ALTER TABLE trucks ADD COLUMN exit_date TEXT");db.execSQL("ALTER TABLE trucks ADD COLUMN border_status TEXT");}
        if(old<3){db.execSQL("CREATE TABLE IF NOT EXISTS status_history (id INTEGER PRIMARY KEY AUTOINCREMENT, truck_id INTEGER NOT NULL, event_date TEXT NOT NULL, status INTEGER NOT NULL, note TEXT, created_at INTEGER)");}
    }
    public long add(String plate,String driver,String phone,String cargo,String owner,String broker,String origin,String parking,String weight,String entry,String exit,String border){ ContentValues v=values(plate,driver,phone,cargo,owner,broker,origin,parking,weight,entry,exit,border); v.put("status",0);v.put("created_at",System.currentTimeMillis());long id=getWritableDatabase().insert("trucks",null,v);if(id>0 && entry!=null&&!entry.isEmpty()) addHistory(id,entry,0,"ثبت اولیه");return id; }
    private ContentValues values(String plate,String driver,String phone,String cargo,String owner,String broker,String origin,String parking,String weight,String entry,String exit,String border){ContentValues v=new ContentValues();v.put("plate",plate);v.put("driver",driver);v.put("phone",phone);v.put("cargo",cargo);v.put("owner",owner);v.put("broker",broker);v.put("origin",origin);v.put("parking",parking);v.put("weight",weight);v.put("entry_date",entry);v.put("exit_date",exit);v.put("border_status",border);return v;}
    public void update(Truck t,String plate,String driver,String phone,String cargo,String owner,String broker,String origin,String parking,String weight,String entry,String exit,String border){getWritableDatabase().update("trucks",values(plate,driver,phone,cargo,owner,broker,origin,parking,weight,entry,exit,border),"id=?",new String[]{String.valueOf(t.id)});}
    public void delete(long id){SQLiteDatabase d=getWritableDatabase();d.delete("status_history","truck_id=?",new String[]{String.valueOf(id)});d.delete("trucks","id=?",new String[]{String.valueOf(id)});}
    public void advance(long id,int status){setStatus(id,Math.min(status+1,STATUSES.length-1));}
    public void setStatus(long id,int status){ContentValues v=new ContentValues();v.put("status",status);getWritableDatabase().update("trucks",v,"id=?",new String[]{String.valueOf(id)});}
    public long addHistory(long truckId,String date,int status,String note){ContentValues v=new ContentValues();v.put("truck_id",truckId);v.put("event_date",date);v.put("status",status);v.put("note",note);v.put("created_at",System.currentTimeMillis());long id=getWritableDatabase().insert("status_history",null,v);setStatus(truckId,status);return id;}
    public void updateHistory(long id,long truckId,String date,int status,String note){ContentValues v=new ContentValues();v.put("event_date",date);v.put("status",status);v.put("note",note);getWritableDatabase().update("status_history",v,"id=?",new String[]{String.valueOf(id)});recalculateStatus(truckId);}
    public void deleteHistory(long id,long truckId){getWritableDatabase().delete("status_history","id=?",new String[]{String.valueOf(id)});recalculateStatus(truckId);}
    private void recalculateStatus(long truckId){Cursor c=getReadableDatabase().rawQuery("SELECT status FROM status_history WHERE truck_id=? ORDER BY event_date DESC, id DESC LIMIT 1",new String[]{String.valueOf(truckId)});if(c.moveToFirst())setStatus(truckId,c.getInt(0));c.close();}
    public List<StatusEvent> history(long truckId){List<StatusEvent> out=new ArrayList<>();Cursor c=getReadableDatabase().rawQuery("SELECT id,event_date,status,note FROM status_history WHERE truck_id=? ORDER BY event_date ASC,id ASC",new String[]{String.valueOf(truckId)});while(c.moveToNext())out.add(new StatusEvent(c.getLong(0),truckId,c.getString(1),c.getInt(2),c.getString(3)));c.close();return out;}
    public List<Truck> all(String query){List<Truck> out=new ArrayList<>();String q="%"+query+"%";Cursor c=getReadableDatabase().rawQuery("SELECT id,plate,driver,phone,cargo,owner,broker,origin,parking,weight,status,entry_date,exit_date,border_status FROM trucks WHERE plate LIKE ? OR driver LIKE ? OR owner LIKE ? OR cargo LIKE ? ORDER BY id DESC",new String[]{q,q,q,q});while(c.moveToNext())out.add(new Truck(c.getLong(0),c.getString(1),c.getString(2),c.getString(3),c.getString(4),c.getString(5),c.getString(6),c.getString(7),c.getString(8),c.getString(9),c.getInt(10),c.getString(11),c.getString(12),c.getString(13)));c.close();return out;}
    public int countStatus(int status){Cursor c=getReadableDatabase().rawQuery("SELECT COUNT(*) FROM trucks WHERE status=?",new String[]{String.valueOf(status)});int n=c.moveToFirst()?c.getInt(0):0;c.close();return n;}
    public String exportJson(){try{JSONObject root=new JSONObject();JSONArray trucks=new JSONArray();Cursor c=getReadableDatabase().rawQuery("SELECT * FROM trucks ORDER BY id",null);while(c.moveToNext()){JSONObject o=new JSONObject();for(int i=0;i<c.getColumnCount();i++){int type=c.getType(i);if(type==Cursor.FIELD_TYPE_INTEGER)o.put(c.getColumnName(i),c.getLong(i));else o.put(c.getColumnName(i),c.isNull(i)?JSONObject.NULL:c.getString(i));}trucks.put(o);}c.close();root.put("trucks",trucks);JSONArray events=new JSONArray();Cursor e=getReadableDatabase().rawQuery("SELECT * FROM status_history ORDER BY id",null);while(e.moveToNext()){JSONObject o=new JSONObject();for(int i=0;i<e.getColumnCount();i++){int type=e.getType(i);if(type==Cursor.FIELD_TYPE_INTEGER)o.put(e.getColumnName(i),e.getLong(i));else o.put(e.getColumnName(i),e.isNull(i)?JSONObject.NULL:e.getString(i));}events.put(o);}e.close();root.put("status_history",events);return root.toString();}catch(Exception ex){throw new RuntimeException(ex);}}
    public void importJson(String json){try{JSONObject root=new JSONObject(json);SQLiteDatabase d=getWritableDatabase();d.beginTransaction();d.delete("status_history",null,null);d.delete("trucks",null,null);JSONArray trucks=root.optJSONArray("trucks");if(trucks!=null)for(int i=0;i<trucks.length();i++){JSONObject o=trucks.getJSONObject(i);ContentValues v=new ContentValues();String[] cols={"id","plate","driver","phone","cargo","owner","broker","origin","parking","weight","status","created_at","entry_date","exit_date","border_status"};for(String col:cols)if(o.has(col)&&!o.isNull(col))v.put(col,o.getString(col));d.insert("trucks",null,v);}JSONArray events=root.optJSONArray("status_history");if(events!=null)for(int i=0;i<events.length();i++){JSONObject o=events.getJSONObject(i);ContentValues v=new ContentValues();String[] cols={"id","truck_id","event_date","status","note","created_at"};for(String col:cols)if(o.has(col)&&!o.isNull(col))v.put(col,o.getString(col));d.insert("status_history",null,v);}d.setTransactionSuccessful();d.endTransaction();}catch(Exception ex){throw new IllegalArgumentException("فایل پشتیبان معتبر نیست",ex);}}
    public static class StatusEvent{public final long id,truckId;public final String date,note;public final int status;public StatusEvent(long i,long t,String d,int s,String n){id=i;truckId=t;date=d;status=s;note=n;}}
}