package com.mohammadbahrami.border;

import android.content.*;import android.database.Cursor;import android.graphics.Color;import android.graphics.drawable.GradientDrawable;import android.net.Uri;import android.os.*;import android.print.*;import android.view.*;import android.webkit.WebView;import android.widget.*;import androidx.appcompat.app.AppCompatActivity;import java.text.DecimalFormat;

public class MainActivity extends AppCompatActivity{
 DatabaseHelper db; LinearLayout root,body; boolean dark=true; long ownerId,cargoId; String ownerName="",cargoName=""; final int PURPLE=0xff8b2dff;
 public void onCreate(Bundle b){super.onCreate(b);getWindow().getDecorView().setLayoutDirection(View.LAYOUT_DIRECTION_RTL);db=new DatabaseHelper(this);dark=getSharedPreferences("ui",0).getBoolean("dark",true);splash();}
 int bg(){return dark?0xff080811:0xfff6f4fb;} int surface(){return dark?0xff111120:Color.WHITE;} int surface2(){return dark?0xff18152a:0xfff0eafb;} int fg(){return dark?0xfff8f5ff:0xff201a2b;} int muted(){return dark?0xffaaa3ba:0xff71697c;}
 GradientDrawable shape(int color,float r){GradientDrawable g=new GradientDrawable();g.setColor(color);g.setCornerRadius(dp((int)r));return g;}
 GradientDrawable card(){GradientDrawable g=shape(surface(),18);g.setStroke(dp(1),dark?0xff35234e:0xffe7dcf5);return g;}
 TextView tx(String s,int z){TextView v=new TextView(this);v.setText(s);v.setTextSize(z);v.setTextColor(fg());v.setGravity(Gravity.RIGHT|Gravity.CENTER_VERTICAL);v.setPadding(dp(16),dp(10),dp(16),dp(10));return v;}
 TextView icon(String s){TextView v=tx(s,22);v.setGravity(Gravity.CENTER);v.setTextColor(PURPLE);return v;}
 Button primary(String s){Button b=new Button(this);b.setText(s);b.setTextSize(15);b.setTextColor(Color.WHITE);b.setAllCaps(false);b.setBackground(shape(PURPLE,16));return b;}
 void splash(){FrameLayout f=new FrameLayout(this);f.setBackgroundColor(bg());LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.VERTICAL);c.setGravity(Gravity.CENTER);TextView mb=tx("MB",64);mb.setTextColor(PURPLE);mb.setGravity(Gravity.CENTER);mb.setTypeface(null,1);c.addView(mb,new LinearLayout.LayoutParams(-1,dp(105)));TextView n=tx("MOHAMMAD BAHRAMI",22);n.setGravity(Gravity.CENTER);n.setTypeface(null,1);c.addView(n);TextView s=tx("LOGISTICS & CLEARANCE",12);s.setGravity(Gravity.CENTER);s.setTextColor(muted());c.addView(s);f.addView(c,new FrameLayout.LayoutParams(-1,-1));setContentView(f);new Handler(Looper.getMainLooper()).postDelayed(this::home,900);}
 void shell(String title,boolean back){root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(bg());getWindow().setStatusBarColor(bg());getWindow().setNavigationBarColor(bg());
  LinearLayout h=new LinearLayout(this);h.setGravity(Gravity.CENTER_VERTICAL);h.setPadding(dp(8),dp(4),dp(8),0);if(back){TextView b=icon("‹");b.setOnClickListener(v->home());h.addView(b,new LinearLayout.LayoutParams(dp(50),dp(58)));}
  TextView brand=tx("MB",23);brand.setTextColor(PURPLE);brand.setTypeface(null,1);h.addView(brand,new LinearLayout.LayoutParams(dp(60),dp(58)));TextView t=tx(title,20);t.setTypeface(null,1);h.addView(t,new LinearLayout.LayoutParams(0,dp(58),1));TextView th=icon(dark?"☀":"☾");th.setOnClickListener(v->{dark=!dark;getSharedPreferences("ui",0).edit().putBoolean("dark",dark).apply();home();});h.addView(th,new LinearLayout.LayoutParams(dp(52),dp(58)));root.addView(h);
  ScrollView sv=new ScrollView(this);body=new LinearLayout(this);body.setOrientation(LinearLayout.VERTICAL);body.setPadding(dp(16),dp(8),dp(16),dp(28));sv.addView(body);root.addView(sv,new LinearLayout.LayoutParams(-1,0,1));bottom();setContentView(root);
 }
 void bottom(){LinearLayout n=new LinearLayout(this);n.setGravity(Gravity.CENTER);n.setPadding(dp(6),dp(4),dp(6),dp(6));String[] a={"⌂\nخانه","▣\nصاحبان بار","▥\nگزارش‌ها","⚙\nتنظیمات"};for(String s:a){TextView x=tx(s,12);x.setGravity(Gravity.CENTER);if(s.contains("خانه"))x.setTextColor(PURPLE);x.setOnClickListener(v->{String q=((TextView)v).getText().toString();if(q.contains("گزارش"))reports();else home();});n.addView(x,new LinearLayout.LayoutParams(0,dp(62),1));}root.addView(n);}
 void hero(String big,String small){LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.VERTICAL);c.setGravity(Gravity.CENTER);c.setBackground(card());TextView b=tx(big,30);b.setGravity(Gravity.CENTER);b.setTextColor(PURPLE);b.setTypeface(null,1);c.addView(b);TextView s=tx(small,13);s.setGravity(Gravity.CENTER);s.setTextColor(muted());c.addView(s);add(c,0,dp(8));}
 void home(){shell("صاحبان بار",false);hero("MB","MOHAMMAD BAHRAMI  •  LOGISTICS & CLEARANCE");EditText search=input("جستجوی صاحب بار...");body.addView(search,new LinearLayout.LayoutParams(-1,dp(52)));section("صاحبان بار");Cursor c=db.owners();while(c.moveToNext()){long id=c.getLong(0);String n=c.getString(1);int count=c.getInt(2);LinearLayout row=rowCard();row.addView(icon("▦"),new LinearLayout.LayoutParams(dp(52),dp(68)));TextView text=tx(n+"\n"+count+" ماشین",17);text.setTypeface(null,1);row.addView(text,new LinearLayout.LayoutParams(0,dp(68),1));row.addView(icon("‹"),new LinearLayout.LayoutParams(dp(42),dp(68)));row.setOnClickListener(v->{ownerId=id;ownerName=n;cargos();});add(row,dp(5),dp(5));}c.close();Button b=primary("+  افزودن صاحب بار");b.setOnClickListener(v->simpleDialog("صاحب بار جدید","نام صاحب بار",x->{if(!x.isEmpty())db.addOwner(x);home();}));add(b,dp(10),0);}
 LinearLayout rowCard(){LinearLayout r=new LinearLayout(this);r.setGravity(Gravity.CENTER_VERTICAL);r.setBackground(card());return r;}
 void section(String s){TextView x=tx(s,15);x.setTextColor(muted());x.setTypeface(null,1);body.addView(x);}
 void cargos(){shell(ownerName,true);TextView sub=tx("پوشه‌های نوع بار",14);sub.setTextColor(muted());body.addView(sub);Cursor c=db.cargos(ownerId);while(c.moveToNext()){long id=c.getLong(0);String n=c.getString(1),io=c.getString(2),br=c.getString(3),or=c.getString(4);int count=c.getInt(5);LinearLayout r=rowCard();r.addView(icon("▰"),new LinearLayout.LayoutParams(dp(60),dp(82)));TextView t=tx(n+"\n"+count+" ماشین\n"+safe(or),17);t.setTypeface(null,1);r.addView(t,new LinearLayout.LayoutParams(0,dp(82),1));r.addView(icon("⋮"),new LinearLayout.LayoutParams(dp(42),dp(82)));r.setOnClickListener(v->{cargoId=id;cargoName=n;trucks(io,br,or);});add(r,dp(5),dp(5));}c.close();Button b=primary("+  نوع بار جدید");b.setOnClickListener(v->cargoDialog());add(b,dp(10),0);}
 void trucks(String io,String br,String or){shell(cargoName,true);LinearLayout meta=new LinearLayout(this);meta.setOrientation(LinearLayout.VERTICAL);meta.setBackground(card());TextView h=tx("اطلاعات ثابت محموله",16);h.setTextColor(PURPLE);h.setTypeface(null,1);meta.addView(h);meta.addView(tx("صاحب بار عراقی:  "+safe(io)+"\nترخیص‌کار عراقی:  "+safe(br)+"\nمبدأ بارگیری:  "+safe(or),14));add(meta,0,dp(8));Button b=primary("+  ثبت ماشین جدید");b.setOnClickListener(v->truckDialog(io,br,or));add(b,dp(4),dp(8));section("ماشین‌های ثبت‌شده");Cursor c=db.trucks(cargoId);while(c.moveToNext()){String phone=c.getString(3);LinearLayout r=rowCard();TextView t=tx("پلاک  "+c.getString(1)+"     •     "+safe(c.getString(4))+" کیلو\n"+safe(c.getString(2))+"     |     سایز "+safe(c.getString(5)),15);r.addView(t,new LinearLayout.LayoutParams(0,dp(72),1));TextView call=icon("☎");call.setOnClickListener(v->{if(phone!=null&&!phone.isEmpty())startActivity(new Intent(Intent.ACTION_DIAL,Uri.parse("tel:"+phone)));});r.addView(call,new LinearLayout.LayoutParams(dp(56),dp(72)));add(r,dp(4),dp(4));}c.close();}
 void truckActions(long id,String p,String dr,String ph,String w,String sz,long entry,long exit,String st,String io,String br,String or){String[] a={"ویرایش اطلاعات","تغییر وضعیت مرزی","حذف ماشین"};new androidx.appcompat.app.AlertDialog.Builder(this).setTitle(p).setItems(a,(d,which)->{if(which==0)editTruck(id,p,dr,ph,w,sz,entry,exit,st,io,br,or);else if(which==1)statusDialog(id,p,dr,ph,w,sz,entry,exit,io,br,or);else new androidx.appcompat.app.AlertDialog.Builder(this).setTitle("حذف ماشین").setMessage("این ماشین و اطلاعاتش حذف شود؟").setNegativeButton("انصراف",null).setPositiveButton("حذف",(x,y)->{db.deleteTruck(id);trucks(io,br,or);}).show();}).show();}
 void statusDialog(long id,String p,String dr,String ph,String w,String sz,long entry,long exit,String io,String br,String or){String[] st={"تخلیه شده","پارکینگ","باسکول کرده - پارکینگ بالا"};new androidx.appcompat.app.AlertDialog.Builder(this).setTitle("وضعیت در مرز").setItems(st,(d,i)->{db.updateTruck(id,p,dr,ph,w,sz,entry,exit,st[i]);trucks(io,br,or);}).show();}
 void editTruck(long id,String p,String dr,String ph,String w,String sz,long entry,long exit,String st,String io,String br,String or){LinearLayout f=form();EditText ep=input("پلاک"),ew=input("وزن"),es=input("سایز"),eph=input("شماره تماس"),ed=input("نام راننده"),ein=input("تاریخ ورود شمسی"),eout=input("تاریخ خروج شمسی");ep.setText(p);ew.setText(w);es.setText(sz);eph.setText(ph);ed.setText(dr);ein.setText(entry>0?jalali(entry):"");eout.setText(exit>0?jalali(exit):"");f.addView(ep);f.addView(ew);f.addView(es);f.addView(eph);f.addView(ed);f.addView(ein);f.addView(eout);new androidx.appcompat.app.AlertDialog.Builder(this).setTitle("ویرایش ماشین").setView(f).setNegativeButton("انصراف",null).setPositiveButton("ذخیره",(d,x)->{long en=parseJalali(val(ein),entry),ex=parseJalali(val(eout),exit);db.updateTruck(id,val(ep),val(ed),val(eph),val(ew),val(es),en,ex,st);trucks(io,br,or);}).show();}
 String jalali(long ms){java.util.Calendar c=java.util.Calendar.getInstance();c.setTimeInMillis(ms);int[] j=DatabaseHelper.Jalali.toJalali(c.get(java.util.Calendar.YEAR),c.get(java.util.Calendar.MONTH)+1,c.get(java.util.Calendar.DAY_OF_MONTH));return j[0]+"/"+String.format(java.util.Locale.US,"%02d",j[1])+"/"+String.format(java.util.Locale.US,"%02d",j[2]);}
 long parseJalali(String s,long fallback){try{String[] x=s.split("/");int[] g=DatabaseHelper.Jalali.toGregorian(Integer.parseInt(x[0]),Integer.parseInt(x[1]),Integer.parseInt(x[2]));java.util.Calendar c=java.util.Calendar.getInstance();c.clear();c.set(g[0],g[1]-1,g[2]);return c.getTimeInMillis();}catch(Exception e){return fallback;}}
 void cargoDialog(){LinearLayout f=form();EditText n=input("نام نوع بار"),io=input("صاحب بار عراقی"),br=input("ترخیص‌کار عراقی"),or=input("مبدأ بارگیری");f.addView(n);f.addView(io);f.addView(br);f.addView(or);new androidx.appcompat.app.AlertDialog.Builder(this).setTitle("افزودن نوع بار جدید").setView(f).setNegativeButton("انصراف",null).setPositiveButton("ثبت",(d,w)->{if(!val(n).isEmpty())db.addCargo(ownerId,val(n),val(io),val(br),val(or));cargos();}).show();}
 void truckDialog(String io,String br,String or){LinearLayout f=form();EditText p=input("پلاک"),w=input("وزن"),s=input("سایز"),ph=input("شماره تماس"),dr=input("نام راننده");ph.setInputType(3);f.addView(p);f.addView(w);f.addView(s);f.addView(ph);f.addView(dr);new androidx.appcompat.app.AlertDialog.Builder(this).setTitle("ثبت ماشین جدید").setView(f).setNegativeButton("انصراف",null).setPositiveButton("ثبت",(d,x)->{if(!val(p).isEmpty())db.addTruck(cargoId,val(p),val(dr),val(ph),val(w),val(s));trucks(io,br,or);}).show();}
 void reports(){int[] td=DatabaseHelper.Jalali.today();shell("گزارش‌ها",true);hero(""+td[0],"گزارش سالانه و ماهانه");String[] m={"فروردین","اردیبهشت","خرداد","تیر","مرداد","شهریور","مهر","آبان","آذر","دی","بهمن","اسفند"};LinearLayout grid=null;for(int i=1;i<=12;i++){if((i-1)%2==0){grid=new LinearLayout(this);body.addView(grid,new LinearLayout.LayoutParams(-1,-2));}final int mm=i;Cursor c=db.monthly(td[0],i);int n=c.getCount();c.close();TextView x=tx(m[i-1]+"\n"+n+" ماشین",16);x.setGravity(Gravity.CENTER);x.setBackground(card());x.setOnClickListener(v->month(td[0],mm,m[mm-1]));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(0,dp(82),1);p.setMargins(dp(4),dp(4),dp(4),dp(4));grid.addView(x,p);}}
 void month(int y,int m,String mn){shell("گزارش "+mn,true);Cursor c=db.monthly(y,m);int n=c.getCount();double total=0;StringBuilder html=new StringBuilder("<html dir='rtl'><meta charset='utf-8'><style>body{font-family:sans-serif;padding:28px}h1{color:#8b2dff}table{width:100%;border-collapse:collapse}td,th{border:1px solid #bbb;padding:7px}</style><h1>MB • MOHAMMAD BAHRAMI</h1><h2>گزارش "+mn+" "+y+"</h2><table><tr><th>صاحب بار</th><th>نوع بار</th><th>پلاک</th><th>راننده</th><th>وزن</th></tr>");while(c.moveToNext()){try{total+=Double.parseDouble(c.getString(5).replace(",",""));}catch(Exception e){}html.append("<tr><td>").append(c.getString(0)).append("</td><td>").append(c.getString(1)).append("</td><td>").append(c.getString(2)).append("</td><td>").append(safe(c.getString(3))).append("</td><td>").append(safe(c.getString(5))).append("</td></tr>");}c.close();hero(n+" ماشین","مجموع وزن  "+new DecimalFormat("#,###").format(total)+" کیلوگرم");Button p=primary("⇩  دریافت گزارش PDF");String h=html.append("</table></html>").toString();p.setOnClickListener(v->pdf(h,mn+"-"+y));add(p,dp(10),0);}
 void pdf(String html,String name){WebView w=new WebView(this);w.loadDataWithBaseURL(null,html,"text/html","UTF-8",null);w.setWebViewClient(new android.webkit.WebViewClient(){public void onPageFinished(WebView v,String u){((PrintManager)getSystemService(PRINT_SERVICE)).print("MB-"+name,v.createPrintDocumentAdapter("گزارش-"+name),new PrintAttributes.Builder().setMediaSize(PrintAttributes.MediaSize.ISO_A4).build());}});}
 interface Done{void go(String s);}void simpleDialog(String title,String hint,Done d){EditText x=input(hint);new androidx.appcompat.app.AlertDialog.Builder(this).setTitle(title).setView(x).setNegativeButton("انصراف",null).setPositiveButton("ثبت",(a,b)->d.go(val(x))).show();}
 EditText input(String h){EditText e=new EditText(this);e.setHint(h);e.setTextColor(fg());e.setHintTextColor(muted());e.setSingleLine();e.setPadding(dp(16),0,dp(16),0);e.setBackground(card());LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,dp(52));p.setMargins(0,dp(5),0,dp(5));e.setLayoutParams(p);return e;}
 LinearLayout form(){LinearLayout f=new LinearLayout(this);f.setOrientation(LinearLayout.VERTICAL);f.setPadding(dp(20),dp(8),dp(20),dp(8));return f;}void add(View v,int top,int bottom){LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.setMargins(0,top,0,bottom);body.addView(v,p);}String val(EditText e){return e.getText().toString().trim();}String safe(String s){return s==null||s.isEmpty()?"—":s;}int dp(int n){return(int)(n*getResources().getDisplayMetrics().density+.5f);}
}