package com.mohammadbahrami.border;

import android.content.*;import android.database.Cursor;import android.graphics.*;import android.graphics.drawable.GradientDrawable;import android.net.Uri;import android.os.*;import android.print.*;import android.view.*;import android.webkit.WebView;import android.widget.*;import androidx.appcompat.app.AppCompatActivity;import java.text.*;import java.util.*;

public class MainActivity extends AppCompatActivity{
 DatabaseHelper db; LinearLayout root,body; boolean dark=true; long ownerId,cargoId; String ownerName="",cargoName=""; int purple=Color.rgb(139,45,255);
 public void onCreate(Bundle b){super.onCreate(b);getWindow().getDecorView().setLayoutDirection(View.LAYOUT_DIRECTION_RTL);db=new DatabaseHelper(this);dark=getPreferences(0).getBoolean("dark",true);home();}
 int bg(){return dark?Color.rgb(8,8,20):Color.rgb(247,248,253);} int fg(){return dark?Color.WHITE:Color.rgb(25,25,38);} int card(){return dark?Color.rgb(20,20,40):Color.WHITE;} int sub(){return dark?0xffaaa8bb:0xff666477;}
 TextView t(String s,int z){TextView v=new TextView(this);v.setText(s);v.setTextSize(z);v.setTextColor(fg());v.setPadding(d(14),d(12),d(14),d(12));return v;}
 GradientDrawable box(){GradientDrawable g=new GradientDrawable();g.setColor(card());g.setCornerRadius(d(16));g.setStroke(d(1),dark?0xff38334f:0xffe5e2ee);return g;}
 Button btn(String s){Button b=new Button(this);b.setText(s);b.setTextColor(Color.WHITE);b.setTextSize(15);GradientDrawable g=new GradientDrawable();g.setColor(purple);g.setCornerRadius(d(14));b.setBackground(g);return b;}
 void shell(String title){root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(bg());LinearLayout h=new LinearLayout(this);h.setGravity(Gravity.CENTER_VERTICAL);if(!title.equals("صاحبان بار")){TextView back=t("‹",32);back.setOnClickListener(v->home());h.addView(back,new LinearLayout.LayoutParams(d(55),d(60)));}TextView logo=t("MB",25);logo.setTextColor(purple);logo.setTypeface(null,1);h.addView(logo);TextView x=t(title,21);x.setTypeface(null,1);h.addView(x,new LinearLayout.LayoutParams(0,d(70),1));TextView theme=t(dark?"☀":"☾",25);theme.setOnClickListener(v->{dark=!dark;getPreferences(0).edit().putBoolean("dark",dark).apply();home();});h.addView(theme);root.addView(h);ScrollView sv=new ScrollView(this);body=new LinearLayout(this);body.setOrientation(LinearLayout.VERTICAL);body.setPadding(d(14),d(4),d(14),d(90));sv.addView(body);root.addView(sv,new LinearLayout.LayoutParams(-1,0,1));setContentView(root);getWindow().setStatusBarColor(bg());}
 void home(){shell("صاحبان بار");Button report=btn("گزارش ماهانه  •  PDF");report.setOnClickListener(v->reports());body.addView(report,new LinearLayout.LayoutParams(-1,d(55)));TextView hint=t("لیست صاحبان بار",18);hint.setTextColor(sub());body.addView(hint);Cursor c=db.owners();while(c.moveToNext()){long id=c.getLong(0);String n=c.getString(1);TextView r=t("▣  "+n+"\n     "+c.getInt(2)+" ماشین",18);r.setBackground(box());r.setOnClickListener(v->{ownerId=id;ownerName=n;cargos();});add(r);}c.close();Button add=btn("+  صاحب بار جدید");add.setOnClickListener(v->input("صاحب بار جدید","نام صاحب بار",x->{if(!x.isEmpty())db.addOwner(x);home();}));body.addView(add,new LinearLayout.LayoutParams(-1,d(58)));}
 void cargos(){shell(ownerName+"  •  محموله‌ها");Cursor c=db.cargos(ownerId);while(c.moveToNext()){long id=c.getLong(0);String n=c.getString(1);TextView r=t("📁  "+n+"\n     "+c.getInt(5)+" ماشین",19);r.setBackground(box());r.setOnClickListener(v->{cargoId=id;cargoName=n;trucks();});add(r);}c.close();Button b=btn("+  نوع بار جدید");b.setOnClickListener(v->cargoDialog());body.addView(b,new LinearLayout.LayoutParams(-1,d(58)));}
 void cargoDialog(){LinearLayout f=form();EditText n=e("نام نوع بار (مثلاً کاشی / متفرقه)"),io=e("صاحب بار عراقی"),br=e("ترخیص‌کار عراقی"),or=e("مبدأ بارگیری");f.addView(n);f.addView(io);f.addView(br);f.addView(or);new androidx.appcompat.app.AlertDialog.Builder(this).setTitle("افزودن نوع بار").setView(f).setNegativeButton("انصراف",null).setPositiveButton("ثبت",(d,w)->{if(!n.getText().toString().trim().isEmpty())db.addCargo(ownerId,val(n),val(io),val(br),val(or));cargos();}).show();}
 void trucks(){shell(ownerName+"  /  "+cargoName);Button b=btn("+  ثبت ماشین جدید");b.setOnClickListener(v->truckDialog());body.addView(b,new LinearLayout.LayoutParams(-1,d(58)));Cursor c=db.trucks(cargoId);while(c.moveToNext()){String phone=c.getString(3);TextView r=t("پلاک  "+c.getString(1)+"     وزن "+safe(c.getString(4))+"     سایز "+safe(c.getString(5))+"\nراننده: "+safe(c.getString(2))+"     ☎ "+safe(phone),16);r.setBackground(box());r.setOnClickListener(v->{if(phone!=null&&!phone.isEmpty())startActivity(new Intent(Intent.ACTION_DIAL,Uri.parse("tel:"+phone)));});add(r);}c.close();}
 void truckDialog(){LinearLayout f=form();EditText p=e("پلاک"),w=e("وزن (کیلوگرم)"),s=e("سایز (متر)"),ph=e("شماره تماس راننده"),dr=e("نام راننده");ph.setInputType(3);f.addView(p);f.addView(w);f.addView(s);f.addView(ph);f.addView(dr);new androidx.appcompat.app.AlertDialog.Builder(this).setTitle("ثبت ماشین جدید").setView(f).setNegativeButton("انصراف",null).setPositiveButton("ثبت",(d,x)->{if(!val(p).isEmpty())db.addTruck(cargoId,val(p),val(dr),val(ph),val(w),val(s));trucks();}).show();}
 void reports(){int[] td=DatabaseHelper.Jalali.today();shell("گزارش‌های ماهانه  "+td[0]);String[] m={"فروردین","اردیبهشت","خرداد","تیر","مرداد","شهریور","مهر","آبان","آذر","دی","بهمن","اسفند"};for(int i=1;i<=12;i++){final int mm=i;Cursor c=db.monthly(td[0],i);int n=c.getCount();c.close();TextView r=t(m[i-1]+"     "+n+" ماشین",18);r.setBackground(box());r.setOnClickListener(v->month(td[0],mm,m[mm-1]));add(r);}}
 void month(int y,int m,String mn){shell("گزارش "+mn+" "+y);Cursor c=db.monthly(y,m);int n=c.getCount();double total=0;StringBuilder html=new StringBuilder("<html dir='rtl'><meta charset='utf-8'><style>body{font-family:sans-serif;padding:28px}table{width:100%;border-collapse:collapse}td,th{border:1px solid #aaa;padding:7px}h1{color:#7628df}</style><h1>MB - Mohammad Bahrami</h1><h2>گزارش "+mn+" "+y+"</h2><table><tr><th>صاحب بار</th><th>نوع بار</th><th>پلاک</th><th>راننده</th><th>وزن</th><th>سایز</th></tr>");while(c.moveToNext()){try{total+=Double.parseDouble(c.getString(5).replace(",",""));}catch(Exception e){}html.append("<tr><td>").append(c.getString(0)).append("</td><td>").append(c.getString(1)).append("</td><td>").append(c.getString(2)).append("</td><td>").append(safe(c.getString(3))).append("</td><td>").append(safe(c.getString(5))).append("</td><td>").append(safe(c.getString(6))).append("</td></tr>");}c.close();html.append("</table></html>");TextView sum=t("تعداد کل ماشین‌ها: "+n+"\nمجموع وزن: "+new DecimalFormat("#,###").format(total)+" کیلوگرم",22);sum.setBackground(box());body.addView(sum);Button pdf=btn("خروجی PDF");String h=html.toString();pdf.setOnClickListener(v->pdf(h,mn+"-"+y));body.addView(pdf,new LinearLayout.LayoutParams(-1,d(58)));}
 void pdf(String html,String name){WebView w=new WebView(this);w.loadDataWithBaseURL(null,html,"text/html","UTF-8",null);w.setWebViewClient(new android.webkit.WebViewClient(){public void onPageFinished(WebView v,String u){PrintManager pm=(PrintManager)getSystemService(PRINT_SERVICE);pm.print("MB-"+name,v.createPrintDocumentAdapter("گزارش-"+name),new PrintAttributes.Builder().setMediaSize(PrintAttributes.MediaSize.ISO_A4).build());}});}
 interface Done{void go(String s);}void input(String title,String hint,Done done){EditText x=e(hint);new androidx.appcompat.app.AlertDialog.Builder(this).setTitle(title).setView(x).setNegativeButton("انصراف",null).setPositiveButton("ثبت",(d,w)->done.go(val(x))).show();}
 LinearLayout form(){LinearLayout f=new LinearLayout(this);f.setOrientation(LinearLayout.VERTICAL);f.setPadding(d(20),0,d(20),0);return f;}EditText e(String h){EditText x=new EditText(this);x.setHint(h);x.setSingleLine();x.setPadding(d(12),d(8),d(12),d(8));return x;}void add(View v){LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.setMargins(0,d(5),0,d(7));body.addView(v,p);}String val(EditText e){return e.getText().toString().trim();}String safe(String s){return s==null||s.isEmpty()?"—":s;}int d(int x){return(int)(x*getResources().getDisplayMetrics().density+.5f);}
}